print("artith metic operation using fun")
print("---------------")
x=int(input("enter the first no"))
y=int(input("enter the second no"))
      addition(x,y)
      subtraction(x,y)
      multiplecation(x,y)
      division(x,y)
      modules(x,y)
